version: "3.1"
services:
  docker-for-dev:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    environment:
      DEFAULT_HOST: exampleweb.me.local

  example-web:
    image: nginx
    volumes:
      - "./example-web/:/usr/share/nginx/html"
    environment:
      VIRTUAL_HOST: exampleweb.me.local
      VIRTUAL_PORT: 80
    expose:
      - "80"
networks:
  default:
    external:
      name: nginx-proxy
